resolve: do not crash on empty mergestate
I managed to get an empty .hg/merge/state file by interrupting a merge
by pressing Control-C. This lead to this error:

  TypeError: a2b_hex() argument 1 must be string or read-only buffer,
  not None

since localnode is assigned None before the iteration over lines in
the mergestate begins.